plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.company'
version = '1.0.0'

dependencies {
    api project(':outbox-core')
    
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa:4.0.0-RC1'
    implementation 'org.springframework.kafka:spring-kafka:3.3.0-RC1'
    implementation 'org.springframework.boot:spring-boot-autoconfigure:4.0.0-RC1'
    
    compileOnly 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'
    
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.0'
    
    testImplementation 'org.springframework.boot:spring-boot-starter-test:4.0.0-RC1'
    testImplementation 'org.springframework.kafka:spring-kafka-test:3.3.0-RC1'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.9.2'
    testImplementation 'org.junit.platform:junit-platform-launcher:1.9.2'
}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}