/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package vroong.laas.common.event.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** 공통 Kafka 이벤트 래퍼. 모든 도메인 이벤트를 감싸는 표준 구조 */
@org.apache.avro.specific.AvroGenerated
public class KafkaEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5356340895995219834L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"KafkaEvent\",\"namespace\":\"vroong.laas.common.event.avro\",\"doc\":\"공통 Kafka 이벤트 래퍼. 모든 도메인 이벤트를 감싸는 표준 구조\",\"fields\":[{\"name\":\"eventId\",\"type\":\"string\",\"doc\":\"이벤트 고유 식별자 (UUID)\"},{\"name\":\"type\",\"type\":\"string\",\"doc\":\"이벤트 타입 (예: order.order.created)\"},{\"name\":\"source\",\"type\":\"string\",\"doc\":\"이벤트 발행 소스 (예: ORDER, DELIVERY, DISPATCH)\"},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"이벤트 발행 시각 (epoch millis)\"},{\"name\":\"payload\",\"type\":[\"null\",\"bytes\"],\"doc\":\"실제 이벤트 데이터 (직렬화된 페이로드)\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<KafkaEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<KafkaEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<KafkaEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<KafkaEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<KafkaEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this KafkaEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a KafkaEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a KafkaEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static KafkaEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** 이벤트 고유 식별자 (UUID) */
  private java.lang.CharSequence eventId;
  /** 이벤트 타입 (예: order.order.created) */
  private java.lang.CharSequence type;
  /** 이벤트 발행 소스 (예: ORDER, DELIVERY, DISPATCH) */
  private java.lang.CharSequence source;
  /** 이벤트 발행 시각 (epoch millis) */
  private java.time.Instant timestamp;
  /** 실제 이벤트 데이터 (직렬화된 페이로드) */
  private java.nio.ByteBuffer payload;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public KafkaEvent() {}

  /**
   * All-args constructor.
   * @param eventId 이벤트 고유 식별자 (UUID)
   * @param type 이벤트 타입 (예: order.order.created)
   * @param source 이벤트 발행 소스 (예: ORDER, DELIVERY, DISPATCH)
   * @param timestamp 이벤트 발행 시각 (epoch millis)
   * @param payload 실제 이벤트 데이터 (직렬화된 페이로드)
   */
  public KafkaEvent(java.lang.CharSequence eventId, java.lang.CharSequence type, java.lang.CharSequence source, java.time.Instant timestamp, java.nio.ByteBuffer payload) {
    this.eventId = eventId;
    this.type = type;
    this.source = source;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.payload = payload;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return type;
    case 2: return source;
    case 3: return timestamp;
    case 4: return payload;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = (java.lang.CharSequence)value$; break;
    case 1: type = (java.lang.CharSequence)value$; break;
    case 2: source = (java.lang.CharSequence)value$; break;
    case 3: timestamp = (java.time.Instant)value$; break;
    case 4: payload = (java.nio.ByteBuffer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return 이벤트 고유 식별자 (UUID)
   */
  public java.lang.CharSequence getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * 이벤트 고유 식별자 (UUID)
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return 이벤트 타입 (예: order.order.created)
   */
  public java.lang.CharSequence getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * 이벤트 타입 (예: order.order.created)
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'source' field.
   * @return 이벤트 발행 소스 (예: ORDER, DELIVERY, DISPATCH)
   */
  public java.lang.CharSequence getSource() {
    return source;
  }


  /**
   * Sets the value of the 'source' field.
   * 이벤트 발행 소스 (예: ORDER, DELIVERY, DISPATCH)
   * @param value the value to set.
   */
  public void setSource(java.lang.CharSequence value) {
    this.source = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return 이벤트 발행 시각 (epoch millis)
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * 이벤트 발행 시각 (epoch millis)
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'payload' field.
   * @return 실제 이벤트 데이터 (직렬화된 페이로드)
   */
  public java.nio.ByteBuffer getPayload() {
    return payload;
  }


  /**
   * Sets the value of the 'payload' field.
   * 실제 이벤트 데이터 (직렬화된 페이로드)
   * @param value the value to set.
   */
  public void setPayload(java.nio.ByteBuffer value) {
    this.payload = value;
  }

  /**
   * Creates a new KafkaEvent RecordBuilder.
   * @return A new KafkaEvent RecordBuilder
   */
  public static vroong.laas.common.event.avro.KafkaEvent.Builder newBuilder() {
    return new vroong.laas.common.event.avro.KafkaEvent.Builder();
  }

  /**
   * Creates a new KafkaEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new KafkaEvent RecordBuilder
   */
  public static vroong.laas.common.event.avro.KafkaEvent.Builder newBuilder(vroong.laas.common.event.avro.KafkaEvent.Builder other) {
    if (other == null) {
      return new vroong.laas.common.event.avro.KafkaEvent.Builder();
    } else {
      return new vroong.laas.common.event.avro.KafkaEvent.Builder(other);
    }
  }

  /**
   * Creates a new KafkaEvent RecordBuilder by copying an existing KafkaEvent instance.
   * @param other The existing instance to copy.
   * @return A new KafkaEvent RecordBuilder
   */
  public static vroong.laas.common.event.avro.KafkaEvent.Builder newBuilder(vroong.laas.common.event.avro.KafkaEvent other) {
    if (other == null) {
      return new vroong.laas.common.event.avro.KafkaEvent.Builder();
    } else {
      return new vroong.laas.common.event.avro.KafkaEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for KafkaEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<KafkaEvent>
    implements org.apache.avro.data.RecordBuilder<KafkaEvent> {

    /** 이벤트 고유 식별자 (UUID) */
    private java.lang.CharSequence eventId;
    /** 이벤트 타입 (예: order.order.created) */
    private java.lang.CharSequence type;
    /** 이벤트 발행 소스 (예: ORDER, DELIVERY, DISPATCH) */
    private java.lang.CharSequence source;
    /** 이벤트 발행 시각 (epoch millis) */
    private java.time.Instant timestamp;
    /** 실제 이벤트 데이터 (직렬화된 페이로드) */
    private java.nio.ByteBuffer payload;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(vroong.laas.common.event.avro.KafkaEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.source)) {
        this.source = data().deepCopy(fields()[2].schema(), other.source);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.payload)) {
        this.payload = data().deepCopy(fields()[4].schema(), other.payload);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing KafkaEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(vroong.laas.common.event.avro.KafkaEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.source)) {
        this.source = data().deepCopy(fields()[2].schema(), other.source);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.payload)) {
        this.payload = data().deepCopy(fields()[4].schema(), other.payload);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * 이벤트 고유 식별자 (UUID)
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * 이벤트 고유 식별자 (UUID)
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public vroong.laas.common.event.avro.KafkaEvent.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * 이벤트 고유 식별자 (UUID)
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * 이벤트 고유 식별자 (UUID)
      * @return This builder.
      */
    public vroong.laas.common.event.avro.KafkaEvent.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * 이벤트 타입 (예: order.order.created)
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * 이벤트 타입 (예: order.order.created)
      * @param value The value of 'type'.
      * @return This builder.
      */
    public vroong.laas.common.event.avro.KafkaEvent.Builder setType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * 이벤트 타입 (예: order.order.created)
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'type' field.
      * 이벤트 타입 (예: order.order.created)
      * @return This builder.
      */
    public vroong.laas.common.event.avro.KafkaEvent.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'source' field.
      * 이벤트 발행 소스 (예: ORDER, DELIVERY, DISPATCH)
      * @return The value.
      */
    public java.lang.CharSequence getSource() {
      return source;
    }


    /**
      * Sets the value of the 'source' field.
      * 이벤트 발행 소스 (예: ORDER, DELIVERY, DISPATCH)
      * @param value The value of 'source'.
      * @return This builder.
      */
    public vroong.laas.common.event.avro.KafkaEvent.Builder setSource(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.source = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'source' field has been set.
      * 이벤트 발행 소스 (예: ORDER, DELIVERY, DISPATCH)
      * @return True if the 'source' field has been set, false otherwise.
      */
    public boolean hasSource() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'source' field.
      * 이벤트 발행 소스 (예: ORDER, DELIVERY, DISPATCH)
      * @return This builder.
      */
    public vroong.laas.common.event.avro.KafkaEvent.Builder clearSource() {
      source = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * 이벤트 발행 시각 (epoch millis)
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * 이벤트 발행 시각 (epoch millis)
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public vroong.laas.common.event.avro.KafkaEvent.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[3], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * 이벤트 발행 시각 (epoch millis)
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * 이벤트 발행 시각 (epoch millis)
      * @return This builder.
      */
    public vroong.laas.common.event.avro.KafkaEvent.Builder clearTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'payload' field.
      * 실제 이벤트 데이터 (직렬화된 페이로드)
      * @return The value.
      */
    public java.nio.ByteBuffer getPayload() {
      return payload;
    }


    /**
      * Sets the value of the 'payload' field.
      * 실제 이벤트 데이터 (직렬화된 페이로드)
      * @param value The value of 'payload'.
      * @return This builder.
      */
    public vroong.laas.common.event.avro.KafkaEvent.Builder setPayload(java.nio.ByteBuffer value) {
      validate(fields()[4], value);
      this.payload = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'payload' field has been set.
      * 실제 이벤트 데이터 (직렬화된 페이로드)
      * @return True if the 'payload' field has been set, false otherwise.
      */
    public boolean hasPayload() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'payload' field.
      * 실제 이벤트 데이터 (직렬화된 페이로드)
      * @return This builder.
      */
    public vroong.laas.common.event.avro.KafkaEvent.Builder clearPayload() {
      payload = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public KafkaEvent build() {
      try {
        KafkaEvent record = new KafkaEvent();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.source = fieldSetFlags()[2] ? this.source : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.timestamp = fieldSetFlags()[3] ? this.timestamp : (java.time.Instant) defaultValue(fields()[3]);
        record.payload = fieldSetFlags()[4] ? this.payload : (java.nio.ByteBuffer) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<KafkaEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<KafkaEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<KafkaEvent>
    READER$ = (org.apache.avro.io.DatumReader<KafkaEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










